version: '3.4'

services:
  db:
    image: postgres:14.2-alpine
    container_name: db-postgres
    volumes:
      - db:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: redis:alpine3.8
    container_name: redis
    mem_limit: 256m
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"
    restart: on-failure
    logging:
      driver: none

  web:
    container_name: web
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/app:cached
      - app-storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  db: {}
  redis-data: {}
  app-storage: {}

networks:
  default:
    name: financial
